M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date So 14 Jän 2024 22:21:41
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-14T22:21:41+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1378
%
G90
G05
T1
X5.7278Y-5.6848
X5.7278Y-5.8758
T2
X5.847Y-5.673
X5.847Y-5.8876
T3
X2.8313Y-7.2829
M30
